import type { Metadata } from "next";
import "../../globals.css";
import SideBar from "../../../../components/dashboard/LayoutNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return ( <>{children}</> );
}
